import argon2 from 'argon2';
import { afterAll, beforeAll, describe, expect, it } from 'vitest';
import { buildApp, type BuiltApp } from '../src/app.js';
import { loadConfig } from '../src/config.js';
import { withTenant } from '../src/db/client.js';
import { admins, guilds, guildSettings } from '../src/db/schema.js';
import { uuidv7 } from '../src/db/uuid.js';
import { APP_URL } from './helpers/fixtures.js';

/**
 * POST /phases no longer takes a `key` — it's auto-derived from `name`
 * (§ "just the name, internally the ID can be autogenerated").
 */
describe('POST /phases — auto-generated key', () => {
  let app: BuiltApp;
  let guildId: string;
  let adminCookie: string;

  beforeAll(async () => {
    process.env.DATABASE_URL_APP = APP_URL;
    app = await buildApp(loadConfig());
    guildId = uuidv7();
    const slug = `phase-create-${Date.now()}`;
    await app.db.insert(guilds).values({ id: guildId, slug, name: slug, gameVersion: 'tbc', status: 'ACTIVE' });
    await app.db.insert(guildSettings).values({ guildId });
    const passwordHash = await argon2.hash('phase-create-password', { type: argon2.argon2id });
    await withTenant(app.db, guildId, (tx) => tx.insert(admins).values({ id: uuidv7(), guildId, username: 'phaseboss', passwordHash, role: 'LOOT_MASTER' }));
    const login = await app.fastify.inject({ method: 'POST', url: `/api/g/${slug}/auth/login`, payload: { username: 'phaseboss', password: 'phase-create-password' } });
    adminCookie = login.cookies.find((c) => c.name === 'glps_admin_at')!.value;
  });

  afterAll(async () => {
    await app.close();
  });

  it('derives a slug key from the name', async () => {
    const res = await app.fastify.inject({
      method: 'POST',
      url: '/api/phases',
      cookies: { glps_admin_at: adminCookie },
      payload: { name: 'Phase 4 — Naxxramas', gameVersion: 'tbc' },
    });
    expect(res.statusCode, JSON.stringify(res.json())).toBe(200);
    const phaseId = res.json().id as string;
    const get = await app.fastify.inject({ method: 'GET', url: `/api/phases/${phaseId}`, cookies: { glps_admin_at: adminCookie } });
    expect(get.json().key).toBe('phase-4-naxxramas');
  });

  it('appends a numeric suffix on a name collision within the same guild', async () => {
    const first = await app.fastify.inject({
      method: 'POST',
      url: '/api/phases',
      cookies: { glps_admin_at: adminCookie },
      payload: { name: 'Onyxia', gameVersion: 'classic-era' },
    });
    const second = await app.fastify.inject({
      method: 'POST',
      url: '/api/phases',
      cookies: { glps_admin_at: adminCookie },
      payload: { name: 'Onyxia', gameVersion: 'classic-era' },
    });
    expect(first.statusCode).toBe(200);
    expect(second.statusCode).toBe(200);
    const firstGet = await app.fastify.inject({ method: 'GET', url: `/api/phases/${first.json().id}`, cookies: { glps_admin_at: adminCookie } });
    const secondGet = await app.fastify.inject({ method: 'GET', url: `/api/phases/${second.json().id}`, cookies: { glps_admin_at: adminCookie } });
    expect(firstGet.json().key).toBe('onyxia');
    expect(secondGet.json().key).toBe('onyxia-2');
  });

  it('rejects a request that still sends a key field as an unexpected shape only if it fails other validation — key is simply ignored', async () => {
    // zCreatePhase no longer has a `key` field at all; Zod's default (strip
    // unknown keys) means passing one is silently ignored, not rejected.
    const res = await app.fastify.inject({
      method: 'POST',
      url: '/api/phases',
      cookies: { glps_admin_at: adminCookie },
      payload: { key: 'IGNORED', name: 'Blackwing Lair', gameVersion: 'classic-era' },
    });
    expect(res.statusCode).toBe(200);
    const get = await app.fastify.inject({ method: 'GET', url: `/api/phases/${res.json().id}`, cookies: { glps_admin_at: adminCookie } });
    expect(get.json().key).toBe('blackwing-lair');
  });

  it('rejects without an admin session', async () => {
    const res = await app.fastify.inject({ method: 'POST', url: '/api/phases', payload: { name: 'X', gameVersion: 'tbc' } });
    expect(res.statusCode).toBe(401);
  });
});
